---
apiVersion: v1
kind: List
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    name: product
  spec:
    tags:
    - from:
        kind: ImageStreamImage
        name: product@sha256:dcf314addd876be48d683828867b1215157c8a2cae2f36634b278ad893325c73
        namespace: apps
      name: "1.0"
