---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 902290a4a18eb976946cdeb05b5a4388acb9bcde
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: product
    provider: fabric8
    version: "1.0"
    group: com.redhat
  name: product
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: product
    provider: fabric8
    group: com.redhat
